language: node_js
node_js:
- '5.11'
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  app: sheltered-journey-70111
  on: master
  api_key:
    secure: Gl2CrmqG4tleohGJM5sEAo9RanM34XDKnau02WA3CKH3KwDhuzYwRmunAieW9XPK1jETftUMMvBfevNlZQ20i+0bW40nMQS+uQaj6lvvyEaAwTLQjJA0tMVvqoLb23xy9UBMQK5+anSUgwSJnVc3RrzbzY8cGvYpvn9yl9w0R+qwjicK3YAyd3S0leG7qRuDI3uTRM1pCYb1kfnf5P3d0l36hAlfZ/BIl915Z6VeRmXSOT5Wt82fsjcmreKcePd7wYEncIsR9fRDzdEtN+tbiT2cY3h18dbsFzIfe2a7QXaFU771bSmxLO6ixD+ibCaPGGwZ0mI07KGutVFYSNkgW5CC9e8tDMyduOVC7cHXEPXbZPqGaETYahZR0Q7FybRUqQgPZfSipdbtYHut9xG8HvynTHRIUPo3Cy6n+gbI1VFwZmJJeusLehwIXiNv9mEtgZh/a3MxQMTZUAFd6MdepZ6Uflib8Y/OkcT4LJGs6itN8rWJ11CdxYaqSWzlI2Wvcn8tM+JT03V+8IQv9PsHScqBsnYZFzHhT9xDREU14ZHE6vF60xqhCIr2XXGdE5RrbIgMG1ZTflQxIcV6C+aIs+yam+lbgT4iUN8KvfLPp2yhvziyyKy1FkwFRJ8Y4DpZZusdJd59+QYlNc5vnfoNaJRahQPwrLt6cx7A2jR0o+A=
